### PR TITLE
What why how

### PR DESCRIPTION
**Pull request by andrewMacmurray**
Have drafted some stuff for

+ explaining what tachyons is
+ what functional css is
+ why you'd want to use either
+ and how to get set up with tachyons

let me know if this is any use. Comments, edits, additions, rewrites all welcome 😄

### CODE REVIEW

**Comment by nelsonic** [comment]
@andrewMacmurray this is _incredible_! 😍 🎉 
`thank you so much` 🌟

**Comment by andrewMacmurray** [comment]
@nelsonic no worries, hope it will be of some use 😄

**Comment by harrygfox** [comment]
@andrewMacmurray this really is incredible! 💘

**Comment by andrewMacmurray** [comment]
thanks @harrygfox 😄 glad you like

**Pull request merged**
